name: RSpec
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: plangoab_api_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --path vendor/bundle --without production
      # - name: Set env
      #   run: |
      #     echo '::set-env name=RAILS_ENV::test'
      #     echo '::set-env name=DATABASE_URL::postgres://postgres:postgres@localhost:5432/my_database'
      - name: Setup DB
        run: |
          bundle exec rails db:schema:load
      - name: Run tests
        run: bundle exec rspec
